# NeoSolarized Dark

[colors]
background = "#001217"
foreground = "#708183"

cursor_bg = "#708183"

selection_bg = "#fcf4dc"
selection_fg = "#001e26"

[colors.tab_bar]
background = "#073642"

[colors.tab_bar.active_tab]
fg_color = "#181926"
bg_color = "#268bd2"

[colors.tab_bar.inactive_tab]
fg_color = "#CAD3F5"
bg_color = "#586e75"

ansi = [ "#002b36", "#dc322f", "#859900", "#b58900", "#268bd2", "#d33682", "#2aa198", "#e9e2cb" ]
brights = [ "#001e26", "#cb4b16", "#465a61", "#52676f", "#708183", "#6c71c4", "#81908f", "#fcf4dc" ]

[metadata]
name = 'NeoSolarized Dark'
