github.com:
    git_protocol: ssh
    users:
        pv-jeff:
    user: pv-jeff
pv.github.com:
    git_protocol: ssh
    users:
        pv-jeff:
    user: pv-jeff
personal.github.com:
    git_protocol: ssh
    users:
        jeffbuttars:
    user: jeffbuttars
