#!/usr/bin/env bash

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific aliases and functions

# don't put duplicate lines in the history. See bash(1) for more options
#export HISTCONTROL=ignoredups
# ... and ignore same successive entries.
export HISTCONTROL=ignoredups
# Keep a long history
export HISTSIZE=10000000
export HISTFILESIZE=1000000000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set up colors to work with based on the term type
#start out with some generic BASH, xterm stuff so we don't get undefines
BLACK="\033[0;30m"
DARKGRAY="\033[1;30m"
BLUE="\033[0;34m"
LIGHTBLUE="\033[1;34m"
GREEN="\033[0;32m"
LIGHTGREEN="\033[1;32m"
CYAN="\033[0;36m"
LIGHTCYAN="\033[1;36m"
RED="\033[0;31m"
LIGHTRED="\033[1;31m"
PURPLE="\033[0;35m"
LIGHTPURPLE="\033[1;35m"
BROWN="\033[0;33m"
YELLOW="\033[1;33m"
LIGHTGRAY="\033[0;37m"
WHITE="\033[1;37m"
END="\033[0m"

if [ -z "$TERM_META" ]; then
    export TERM_META='light'
fi

TC_HOSTNAME=$LIGHTGREEN
TC_CDIR=$LIGHTCYAN
TC_PROMPT=$LIGHTRED
TC_PROMPT_DELIM=$LIGHTCYAN

if [ -n "$TERM_META" ]; then
    if [[ $TERM_META =~ 'white' ]]; then
        TC_HOSTNAME=$GREEN
        TC_CDIR=$CYAN
        TC_PROMPT=$RED
        TC_PROMPT_DELIM=$CYAN
    fi
fi

if [[ -z $(command -v starship) ]]; then
    if [ "$TERM" != "linux" ]; then
        PROMPT_COMMAND='echo -ne "\033]0;$HOSTNAME : $PWD\007$TC_HOSTNAME$HOSTNAME$END:$TC_CDIR$PWD$END\n"'
    else
        PROMPT_COMMAND='echo -ne "$TC_HOSTNAME$HOSTNAME$END:$TC_CDIR$PWD$END\n"'
    fi

    PS1="\[$TC_PROMPT\]\u\[$END\] \[$TC_PROMPT_DELIM\]>\[$END\] "
fi

#LSCOLORS       The value of this variable describes what color to use
#for which attribute when colors are enabled with
#CLICOLOR.  This string is a concatenation of pairs of the
#format fb, where f is the foreground color and b is the
#background color.

#The color designators are as follows:

#a     black
#b     red
#c     green
#d     brown
#e     blue
#f     magenta
#g     cyan
#h     light grey
#A     bold black, usually shows up as dark grey
#B     bold red
#C     bold green
#D     bold brown, usually shows up as yellow
#E     bold blue
#F     bold magenta
#G     bold cyan
#H     bold light grey; looks like bright white
#x     default foreground or background

#Note that the above are standard ANSI colors.  The actual
#display may differ depending on the color capabilities of
#the terminal in use.

#The order of the attributes are as follows:

#1.   directory
#2.   symbolic link
#3.   socket
#4.   pipe
#5.   executable
#6.   block special
#7.   character special
#8.   executable with setuid bit set
#9.   executable with setgid bit set
#10.  directory writable to others, with sticky bit
#11.  directory writable to others, without sticky
#bit

#The default is "exfxcxdxbxegedabagacad", i.e. blue fore-
#ground and default background for regular directories,
#black foreground and red background for setuid executa-
#bles, etc.
#LS_COLORS='no=00:fi=00:di=01;33:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jpg=01;35:*.gif=01;35:*.bmp=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.png=01;35:*.mpg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:';
#LS_COLORS='no=00:fi=00:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jpg=01;35:*.gif=01;35:*.bmp=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.png=01;35:*.mpg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:';
#export LS_COLORS
export CLICOLOR=1
export LSCOLORS=DxGxcxdxCxegedabagacad

# Setup readline to our tastes
#Use Vi mode
set -o vi

# ^p check for partial match in history
# bind -m vi-insert "\C-p":dynamic-complete-history

# ^n cycle through the list of partial matches
# bind -m vi-insert "\C-n":menu-complete

# Case insensitive completion
#set completion-ignore-case On

set print-completions-horizontally On
set visible-stats On

# colorize man pages
# Don't do this on OS X
if [[ "$OSTYPE" != "Darwin" ]]; then
    export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
    export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
    export LESS_TERMCAP_me=$'\E[0m'           # end mode
    export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
    export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box export LESS_TERMCAP_ue=$'\E[0m' # end underline
    export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline
fi

# Source common rc
if [[ -f "${HOME}/.shell_commonrc" ]]; then
    # shellcheck source=.shell_commonrc
    . "${HOME}/.shell_commonrc"
fi

if [[ -f "${HOME}/.shell.d/index" ]]; then
    # shellcheck source=.shell.d/index
    . "${HOME}/.shell.d/index"
fi
