#!/usr/bin/env bash

export PSQL_EDITOR='vim -c"set ft=sql"'
export BROWSER=google-chrome
export EDITOR='vim'

if [[ "chica" == "$(hostname)" ]]; then
    export POLYBAR_HWMO_TEMP_INPUT='/sys/devices/virtual/thermal/thermal_zone2/temp'
fi
