#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_TOP=$(readlink -f "$THIS_DIR/..")
DOTF_DIR="$REPO_TOP/src/dotfiles"
BIN_DIR="$REPO_TOP/src/bin"

source "$THIS_DIR/upkg.sh"

safe_link()
{
    from=$1
    to=$2
    
    if [[ -f $to ]]; then
        if [[ ! -L $to ]]; then
            mv -f --backup=numbered $to "${to}.bak"
        fi
    fi

    ln -nsf "$from" "$to"
} #safe_link

# install our dotfiles by backing up existing files and linking in our own.
for df in $(ls -1 "$DOTF_DIR/") ; do
    dest="$HOME/.${df}"
    safe_link "$DOTF_DIR/$df" "$dest"
done

# install our bin files by backing up existing files and linking in our own.
for df in $(ls -1 "$BIN_DIR/") ; do
    dest="$HOME/${df}"
    safe_link "$BIN_DIR/$df" "$dest"
done

# Setup vimpager if it's installed
vimpagerdir="$PKGS_PKG_DIR/vimpager" 
if [[ -d $vimpagerdir ]]; then
    pr_info "installing vimpager"
    cd $vimpagerdir

    install -v -D -m 755 vimpager $HOME/bin/vimpager
    install -v -D -m 755 vimcat $HOME/bin/vimcat
    if [[ ! -f $HOME/.vimpagerrc ]]; then
        install -v -D -m 644 vimpagerrc $HOME/.vimpagerrc
    fi
else
    pr_info "didn't find vimpager pager installation at $vimpagerdir"
fi


pr_pass "Run the command 'chsh -s /bin/zsh' to change the default shell to zsh."
