#!/bin/bash

exit 0

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_TOP=$(readlink -f "$THIS_DIR/..")
DOTF_DIR="$REPO_TOP/src/dotfiles"

source "$THIS_DIR/upkg.sh"

# install our dotfiles by backing up existing files and linking in our own.
for df in $(ls -1 "$DOTF_DIR/") ; do
    dest="$HOME/.${df}"
    if [[ -f $dest ]]; then
        if [[ ! -L $dest ]]; then
            mv -f --backup=numbered $dest "${dest}.bak"
        fi
    fi

    ln -nsf "$DOTF_DIR/$df" "$dest"
done

pr_pass "Run the command 'chsh -s /bin/zsh' to change the default shell to zsh."
