[tool.poetry]
name = "jeff.buttars"
version = "0.1.0"
description = ""
authors = ["Jeff Buttars <jeffbuttars@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
python-lsp-server = {extras = ["all"], version = "*"}
pynvim = ">=0.4.3"
black = ">=21.5b2"
mypy = ">=0.812"
immutables = ">=0.15"
pyls-flake8 = ">=0.4.0"
mypy-ls = ">=0.5.1"
pyls-isort = ">=0.2.2"
python-lsp-black = ">=1.0.0"
pyls-memestra = ">=0.0.15"
data-science-types = ">=0.2.19"
isort = "^5.9.3"

[tool.poetry.dev-dependencies]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 99

[tool.flake8]
max-line-length = 99
extend-ignore = "E203, W503"

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "99"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
